---
group:
  - name: Aidan McNay
    netid: acm289
  - name: Andro Janashia
    netid: aj454
  - name: Henry Toll
    netid: hht26

pm:
  name: Noam Benson-Tilsen
  netid: nb498

publish: true

title: "CheckCamelMate"

git-repo: "https://github.com/Aidan-McNay/cs3110-final-project"

demo-video-url: ""

desc: >
  Our project is the classic game of chess implemented using OCaml. 
  It allows players to move and capture pieces just like in a standard
  game of chess. Our program keeps track of all the moves the players make.

  Currently, our project is under developement. Piece movement is supported 
  through a TUI (text user interface). Many game rules are implemented (such
  as basic notions of which moves are valid for which pieces). Advance chess
  rules are not yet implemented (such as notions of check, castling, en passant,
  and promotion). A strong sense of turns is also not yet implemented; users can
  move any piece they wish. Our work-in-progress mainly demonstrates the interactions
  a user can take with a chess board.
